import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { Footer, Header } from "./_components/containers/layout";
import { ModelVersion } from "./_components/containers/model/version";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col h-screen">
          <Header className="px-4 max-w-7xl mx-auto w-full">
            <ModelVersion className="badge badge-secondary">v</ModelVersion>
          </Header>
          <main className="flex-1 overflow-auto px-4 max-w-7xl mx-auto w-full">
            {children}
          </main>
          <Footer className="[&_footer]:px-4 [&_footer]:max-w-7xl [&_footer]:mx-auto [&_footer]:w-full" />
        </div>
      </body>
    </html>
  );
}
